version: '3'
services:
  node:
    build: bitshares-core
    container_name: node
    ports:
     - "127.0.0.1:8090:8090"
     - "9090:9090"
    volumes:
     - "node_data:/data_witness_node"
  faucet:
    build: faucet
    container_name: faucet
    ports:
     - "127.0.0.1:10090:9090"
  wallet:
    build: bitshares-ui
    container_name: wallet
    ports:
     - "127.0.0.1:10080:80"
volumes:
  node_data: {}
